# Generated by Django 3.2.7 on 2021-10-16 03:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default=0, max_length=30, verbose_name='Name')),
                ('prod_artist', models.CharField(default=0, max_length=30, verbose_name='Artist')),
                ('prod_genre', models.CharField(default=0, max_length=15, verbose_name='Genre')),
                ('prod_rate', models.BigIntegerField(verbose_name='Rate')),
                ('prod_type', models.CharField(default=0, max_length=15, verbose_name='Type')),
                ('prod_description', models.CharField(default=0, max_length=50, verbose_name='Description')),
                ('prod_urlproduct', models.CharField(default=0, max_length=15, verbose_name='imagen')),
                ('prod_urlimagen', models.CharField(default=0, max_length=15, verbose_name='imagen')),
                ('prod_state', models.BooleanField(verbose_name='State')),
                ('prod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_producto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favo_id', models.AutoField(primary_key=True, serialize=False)),
                ('favo_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favo_product', to='authApp.product')),
                ('favo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('exch_id', models.AutoField(primary_key=True, serialize=False)),
                ('exch_fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('exch_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exch_prod', to='authApp.product')),
                ('exch_userdestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exch_userdestination', to=settings.AUTH_USER_MODEL)),
                ('exch_userorigin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exch_userorigin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
